// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc-MVXrDzKPNiDZnedIOYONSDrO8uKPXA',
    appId: '1:497672733709:web:f89034d07bdb59bc940144',
    messagingSenderId: '497672733709',
    projectId: 'project-vlu-f890e',
    authDomain: 'project-vlu-f890e.firebaseapp.com',
    storageBucket: 'project-vlu-f890e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUiRIUPZFneWtx0xwjLTCXUGcniXMWyn4',
    appId: '1:497672733709:android:44cba099a5fa6fcd940144',
    messagingSenderId: '497672733709',
    projectId: 'project-vlu-f890e',
    storageBucket: 'project-vlu-f890e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf3QkHGZeqRoO7GHV54mxyc221Q295PLI',
    appId: '1:497672733709:ios:5bc51c25673a0332940144',
    messagingSenderId: '497672733709',
    projectId: 'project-vlu-f890e',
    storageBucket: 'project-vlu-f890e.firebasestorage.app',
    iosBundleId: 'com.health.vlu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf3QkHGZeqRoO7GHV54mxyc221Q295PLI',
    appId: '1:497672733709:ios:53c9efa7a769ff9d940144',
    messagingSenderId: '497672733709',
    projectId: 'project-vlu-f890e',
    storageBucket: 'project-vlu-f890e.firebasestorage.app',
    iosBundleId: 'com.example.vluProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc-MVXrDzKPNiDZnedIOYONSDrO8uKPXA',
    appId: '1:497672733709:web:46bfbe6154583808940144',
    messagingSenderId: '497672733709',
    projectId: 'project-vlu-f890e',
    authDomain: 'project-vlu-f890e.firebaseapp.com',
    storageBucket: 'project-vlu-f890e.firebasestorage.app',
  );

}